version: '3.9'
services:
  rpc-server:
    restart: unless-stopped
    build: rpc-server
    ports:
      - "8888:8888"
    environment:
      - SERVICE_NAME=rpc-server
      - SERVICE_TAGS=rpc
      - POSTGRES_USER=imservice
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-imservice}
      - POSTGRES_HOST=${POSTGRES_DB:-db}
      - POSTGRES_PORT=${POSTGRES_DB:-5432}
    depends_on:
      - etcd
      - db
  http-server:
    build: http-server
    ports:
      - "8080:8080"
    environment:
      - SERVICE_NAME=http-server
      - SERVICE_TAGS=http
    depends_on:
      - etcd
      - rpc-server
  db:
    image: postgres
    environment:
      - POSTGRES_USER=imservice
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-imservice}
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    command: ["etcd", "--advertise-client-urls", "http://etcd:2379", "--listen-client-urls", "http://0.0.0.0:2379"]
    ports:
      - "2379:2379"
